/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

//
//plugins {
//    id("org.jetbrains.kotlin.platform.native") version "1.3.21"
//}

buildscript {
    repositories {
        maven {
            url = uri("https://plugins.gradle.org/m2/")
        }
    }
    dependencies {
        classpath("org.jetbrains.kotlin:kotlin-native-gradle-plugin:1.3.21")
    }
}

apply(plugin = "org.jetbrains.kotlin.platform.native")
